menu:
    Blog: /
    Archive: /archives/
    Weibo: http://weibo.com/missemma777
    GitHub: https://github.com/zpike
    Rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
#disqus: spikezhou
duoshuo: spikezz

# Analytics
# google-analytics:
ga: UA-65933410-1

# Copyright Infomation
startyear: 2016
